// Generated by scripts/build_sw.py. Do not edit this file directly.
const CACHE_PREFIX='prep-hub-assets:'+new URL(self.registration.scope).pathname+':';
const CACHE=CACHE_PREFIX+"8b21ec43dc47";
const ASSETS=["./", "./index.html", "./styles.css", "./app.js", "./state.js", "./sync.js", "./sync-config.js", "./playground.js", "./data/lessons.js", "./data/resources.js", "./data/curriculum.json", "./data/solutions.json", "./manifest.webmanifest", "./icon.svg", "./icon-192.png", "./icon-512.png"];
self.addEventListener('install',event=>{
 event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));
});
self.addEventListener('activate',event=>{
 event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(CACHE_PREFIX)&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));
});
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url);
 if(url.origin!==self.location.origin||!url.href.startsWith(self.registration.scope))return;
 event.respondWith(caches.open(CACHE).then(async cache=>{
  const hit=await cache.match(event.request);
  if(hit)return hit;
  try{return await fetch(event.request);}
  catch(error){
   if(event.request.mode==='navigate')return await cache.match('./index.html');
   throw error;
  }
 }));
});
