"""Generate a versioned offline asset cache from the shipped static files."""
from pathlib import Path
import hashlib, json
root=Path(__file__).resolve().parents[1]
assets=['./','./index.html','./styles.css','./app.js','./state.js','./playground.js','./data/lessons.js','./data/curriculum.json','./data/solutions.json','./manifest.webmanifest','./icon.svg','./icon-192.png','./icon-512.png']
digest=hashlib.sha256()
for asset in assets[1:]:
    digest.update(root.joinpath(asset[2:]).read_bytes())
version=digest.hexdigest()[:12]
source="""// Generated by scripts/build_sw.py. Do not edit this file directly.
const CACHE_PREFIX='prep-hub-assets:'+new URL(self.registration.scope).pathname+':';
const CACHE=CACHE_PREFIX+%s;
const ASSETS=%s;
self.addEventListener('install',event=>{
 event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));
});
self.addEventListener('activate',event=>{
 event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(CACHE_PREFIX)&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));
});
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url);
 if(url.origin!==self.location.origin||!url.href.startsWith(self.registration.scope))return;
 event.respondWith(caches.open(CACHE).then(async cache=>{
  const hit=await cache.match(event.request);
  if(hit)return hit;
  try{return await fetch(event.request);}
  catch(error){
   if(event.request.mode==='navigate')return await cache.match('./index.html');
   throw error;
  }
 }));
});
"""%(json.dumps(version),json.dumps(assets))
root.joinpath('sw.js').write_text(source)
print('Offline cache version:',version)
